### ISSUE TITLE
`Lepton_INCLUDE_DIR` needs adapting for Debian builds

### ISSUE THREAD

**Issue by merkys** [samuelflores/MMB#22]
I am building MMB v3.5 on Debian unstable. Lepton headers are not found unless I patch `CMakeLists.txt`:
```patch
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -45,7 +45,7 @@
 SET(OpenMM_INSTALL_DIR "" CACHE PATH
         "OpenMM install directory. Used to find libs.")
 #Add the OpenMM library
-SET(Lepton_INCLUDE_DIR "/3rdparty/Lepton1.3/include/" CACHE PATH
+SET(Lepton_INCLUDE_DIR "3rdparty/Lepton1.3/include/" CACHE PATH
        "Where to find Lepton includes")
 #Add the Gemmi library path
 SET(GEMMI_INCLUDE_DIR "" CACHE PATH
```
Seemingly, `/` is understood as filesystem root on Debian (all Linux?) systems. It may also be true that the problem is related to newer CMake version (v3.22.0 in Debian unstable right now). Could you please check whether the patch works in your builds as well?

**Comment by MadCatX** [comment]
Absolute paths in Makefiles are always highly suspicious. This looks like it may have been done for the Docker builds which could break with this change.

**Comment by merkys** [comment]
There is this `PROJECT_SOURCE_DIR` CMake variable already in use, maybe it could be used to fix paths for Docker as well?

**Comment by MadCatX** [comment]
The CMakeLists as it is now needs a major cleanup to be able to build MMB correctly on all platforms that are supposed to be supported. I'm afraid that just piling up workarounds is only going to make things worse.

**Comment by samuelflores** [comment]
I agree this is wrong, and should be fixed as Andrius proposes. I have pushed this on git.

It was very likely me that did this. SimTK guys tended to use more slashes than necessary, and I think in this case I carried this over into an inappropriate context. I am not suggesting that SimTK people would make this mistake.

I am not very good at cmake. I wonder, why does this work:

    INCLUDE_DIRECTORIES ( SYSTEM ${Lepton_INCLUDE_DIR} )

? 

Is it prepended with ${PROJECT_SOURCE_DIR}/  implicitly?  cmake does a lot of things implicitly which I think is what makes it so hard to learn and parse.  I think maybe this line may be why it compiles differently on Debian unstable?

**Comment by merkys** [comment]
Thanks for prompt fix, @samuelflores!

> I am not very good at cmake. I wonder, why does this work:
> 
> ```
> INCLUDE_DIRECTORIES ( SYSTEM ${Lepton_INCLUDE_DIR} )
> ```
> 
> ?
> 
> Is it prepended with ${PROJECT_SOURCE_DIR}/ implicitly? cmake does a lot of things implicitly which I think is what makes it so hard to learn and parse. I think maybe this line may be why it compiles differently on Debian unstable?

I have little CMake experience, but I think that relative paths (like `3rdparty/Lepton1.3/include/`) are resolved in the same way the ones with `${PROJECT_SOURCE_DIR}` are. In this case, `${Lepton_INCLUDE_DIR}` is defined as `3rdparty/Lepton1.3/include/` by default, which is a relative path.

Prepending `/` in front of a path may be understood as an absolute path on Linux-type systems. I am not sure how this is handled outside Linux, though.
