### ISSUE TITLE
Differences in parameters.csv

### ISSUE THREAD

**Issue by merkys** [samuelflores/MMB#6]
The repository contains three different variants of `parameters.csv`:

* examples/parameters.csv
* include/resources/parameters.csv
* share/MMB_UI/parameters.csv

First two are nearly identical:
```
$ diff examples/parameters.csv include/resources/parameters.csv 
98c98
< ,RECORD,DG ,DA ,WatsonCrick,Hoogsteen,Cis,N9,C4,C8,,N9,C4,C8,,0,,,,-3,,,,5,-0.722461,-0.531117,0.0419362,1.69488,-0.0662644,-0.136665,-0.988399,baseInteraction,1.11,,
---
> ,RECORD,DG ,DA ,WatsonCrick,Hoogsteen,Cis,N9,C4,C8,,N9,C4,C8,,0,,,,-3,,,,5,-0.354536,0.885708,0.126182,1.57101,-0.00846233,-0.186297,0.982457      ,baseInteraction,1.16,,
100c100
< ,RECORD,DA ,DG ,WatsonCrick,Hoogsteen,Cis,N9,C4,C8,,N9,C4,C8,,0,,,,-3,,,,5,-0.459764,0.728308,0.0665503,1.46754,0.0669876,-0.24912,0.966153,baseInteraction,1.05,,
---
> ,RECORD,DA ,DG ,WatsonCrick,Hoogsteen,Cis,N9,C4,C8,,N9,C4,C8,,0,,,,-3,,,,5,-0.354536,0.885708,0.126182,1.57101,-0.00846233,-0.186297,0.982457      ,baseInteraction,1.16,,
```
Third one is 100 times smaller in size than the first two.

I wonder why they are different, and which of them should be used by default?

**Comment by samuelflores** [comment]
Hi Andrius,

Thanks for finding this problem, and sorry for the error. The one in include/resources is correct.  I have deleted the other two.  The "examples" directory is intended to support the tutorial guide, and users will always need parameters.csv in order for MMB to run at all. But it's a bad idea to have the same file in two places. In particular include/resources is a bizarre place to put such a vital file -- but in any case that is where the one remaining file is (for now). Do you have a suggestion as to a more orthodox final home for this?

Sam

**Comment by merkys** [comment]
To me `include/resources/` seems sensible, as other parameter files are stored there too. As for `examples`, it could contain a symbolic link to `include/resources/parameters.csv` in order to make the tutorial calculations executable directly from this location.

A related question: maybe it would make sense if MMB used `parameters.csv` from `/usr/share/mmb` when the parameters file is not found in the working directory? I assume the most of the users will use the parameters file as is supplied in MMB, without modifying it.

**Comment by samuelflores** [comment]
On Wed, Jun 17, 2020 at 11:48 AM Andrius Merkys <notifications@github.com>
wrote:

> To me include/resources/ seems sensible, as other parameter files are
> stored there too. As for examples, it could contain a symbolic link to
> include/resources/parameters.csv in order to make the tutorial
> calculations executable directly from this location.
>
> A related question: maybe it would make sense if MMB used parameters.csv
> from /usr/share/mmb when the parameters file is not found in the working
> directory? I assume the most of the users will use the parameters file as
> is supplied in MMB, without modifying it.
>
In the overwhelming majority of cases, the users indeed will not modify
parameters.csv. /usr/share/mmb is where I would usually install , but is
that where apt-get would put it? perhaps you mean that this path would be
set at install time, based on the install directory specified in cmake? I
guess future users will either use apt-get or docker so maybe this can
work. i will think about this. I guess it is not very urgent.

Does github support softlinks?  I am a bit worried that these would break
under certain circumstances which I cannot foresee. But that sounds easy
enough if it can be relied upon.

Do you have any updated idea regarding when mmb will become available
through the package manager? really excited about that.

sam

**Comment by merkys** [comment]
> In the overwhelming majority of cases, the users indeed will not modify parameters.csv. /usr/share/mmb is where I would usually install , but is that where apt-get would put it? perhaps you mean that this path would be set at install time, based on the install directory specified in cmake? I guess future users will either use apt-get or docker so maybe this can work. i will think about this. I guess it is not very urgent.

Indeed, I meant the path set at the configure/install stage. Surely this is not at all urgent, I meant this just as a suggestion.

> Does github support softlinks? I am a bit worried that these would break under certain circumstances which I cannot foresee. But that sounds easy enough if it can be relied upon.

I think so, at least I never had any problems with softlinks on git/GitHub. However, I am not sure whether Windows handles them properly.

> Do you have any updated idea regarding when mmb will become available through the package manager? really excited about that.

The earliest this could happen is in Debian 11 (mid-2021, I guess) and Ubuntu 20.10 (October 2020).

**Comment by merkys** [comment]
As the issue with multiple copies of `parameters.csv` has been resolved, I am closing it.
